- README.md
Drupal4Gov/Drupal-GovCon-2017#2
> Added more details to readme including some troubleshooting

- README.md
Added SSH key info to Readme.md
> Readme.md updated for SSH key setup.

- README.md
Drush > 8 added, code correction to SSH key section.
> Added Prerequisite, other edit for clarity

- .gitignore
- composer.json
- composer.lock
- config/default/core.entity_form_display.scheduled_update.multiple_node_embargo.default.yml
- config/default/features.bundle.default.yml
- config/default/features.bundle.lightning.yml
- config/default/features.settings.yml
- config/default/media_entity.bundle.image.yml
- config/default/media_entity.bundle.instagram.yml
Let me know if I missed anything.
> DGC-78: Changed Lightning version in composer. Closes #78

- docroot/themes/custom/twentyseventeen/sass/_config.scss
- docroot/themes/custom/twentyseventeen/sass/components/footer/_footer.scss
- docroot/themes/custom/twentyseventeen/sass/components/footer/footer.json
- docroot/themes/custom/twentyseventeen/sass/components/footer/footer.twig
Basic footer component based on static mockup. #106
> DGC-106 Footer component

- .gitignore
- docroot/themes/custom/twentyseventeen/.gitignore
see https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/143
> DGC-143: updating git ignores so theme deploys properly

- docroot/themes/custom/twentyseventeen/sass/_config.scss
- docroot/themes/custom/twentyseventeen/sass/base/utility/_utility.scss
- docroot/themes/custom/twentyseventeen/sass/components/nav/_nav.scss
- docroot/themes/custom/twentyseventeen/sass/components/nav/nav.json
- docroot/themes/custom/twentyseventeen/sass/components/nav/nav.twig
#105 
- Responsive
- Pure CSS
- Accessible
- Animated
> DGC-105 Responsive menu component

- docroot/modules/custom/capitalcamp_blocks/src/Plugin/Block/DgcNav.php
- docroot/themes/custom/twentyseventeen/sass/base/elements/_elements.scss
- docroot/themes/custom/twentyseventeen/sass/components/nav/_nav.scss
- docroot/themes/custom/twentyseventeen/sass/components/nav/nav.json
- docroot/themes/custom/twentyseventeen/sass/components/nav/nav.twig
#152 
@aweingarten I resolved the same fatal error in the custom nav block at the same time you did and merged yours, so that is why my first commit says I fixed an error but just shows some white space deletions.
> DGC-152 Display child links in nav

- blt/project.yml
This change was made--works as tested.
> Changed local alias so that commands can be run outside of the VM

- docroot/themes/custom/twentyseventeen/sass/components/nav/_nav.scss
> DGC-233 - forgot to target only checkboxes inside of nav

- docroot/themes/custom/twentyseventeen/sass/components/hero/_hero.scss
- docroot/themes/custom/twentyseventeen/sass/components/hero/hero.twig
Call-to-action elements created and styled, links tested.
> DGC-249: Hero CTA elements added and styled.

- docroot/themes/custom/twentyseventeen/sass/components/internalheader/_internalheader.scss
- docroot/themes/custom/twentyseventeen/sass/components/internalheader/internalheader.twig
CTA elements added to internal headers, positioned in top right in desktop view.
> DGC 257 Style Internal Header CTA

- docroot/modules/custom/capitalcamp_glue/capitalcamp_glue.install
> DGC-295: Update Session Tracks to latest terms in update hook.

- docroot/themes/custom/twentyseventeen/sass/base/form/_form.scss
Styling fixed, fieldset labels set to be less prominent, more semantic, less confusing.
> DGC-289: Fieldset labels restyled to be more readable and less confusing

- config/default/system.site.yml
Fixes Drupal4Gov/Drupal-GovCon-2017#335
> Changes site email address from Adam's to Drupal4Gov.

- docroot/themes/custom/twentyseventeen/sass/components/hero/hero.twig
- docroot/themes/custom/twentyseventeen/sass/components/internalheader/internalheader.twig
Fixes Drupal4Gov/Drupal-GovCon-2017#315
> Updated hero button for "Register" to "Tickets"

- config/default/block.block.twentyseventeen_page_title.yml
- config/default/contact.form.contact.yml
- config/default/core.entity_form_display.contact_message.contact.default.yml
- config/default/core.entity_view_display.contact_message.contact.default.yml
- config/default/field.field.contact_message.contact.field_message.yml
- config/default/field.storage.contact_message.field_message.yml
- config/default/webform.webform.contact.yml
Added recaptcha element to form.
> Dgc 312 site contact form add recaptcha

- docroot/themes/custom/twentyseventeen/templates/blocks/block--dgc-intro.html.twig
Fixes Drupal4Gov/Drupal-GovCon-2017#370
> Removed sentence about registration and speaker submissions coming soon.

- box/config.yml
Drush version for VM set to 8.x to avoid issue of installing unstable Drush 9.x in the VM.
> DGC-464: Drush version set in config.yml file.

- config/default/views.view.sessions_schedule.yml
Needed up make an update - view was missing a filter for 'Accepted' or 'Featured' Session status
> dgc-446: Add status filter for Session Schedule - Accepted or Featured

- config/default/core.date_format.day.yml
- config/default/core.entity_view_display.node.session.teaser.yml
- config/default/views.view.sessions_schedule.yml
Config updates and changes by @charlieartist
> DGC-466: Views configuration updates added.

- docroot/themes/custom/twentyseventeen/sass/components/schedule/_schedule.scss
- docroot/themes/custom/twentyseventeen/sass/components/schedule/schedule.twig
UX and layout fixes to schedule display.
Fixes include:
- Select Filter spacing for mobile/visual alignment
- Day tabs fix for mobile display
- Time text size adjusted
- Separator between track and experience level visually improved
> DGC-479 Schedule Updates

- config/default/views.view.attendee_check_in.yml
View was removed in dgc-482. This recovers the view.
> dgc-393: Recover participant check in view - removed by dgc-482

- config/default/core.entity_view_display.node.session.teaser.yml
> dgc-493: Remove link from Session Teaser ‘track’ taxonomy term

- config/default/views.view.user_sessions.yml
Hiding fields on empty and removed no results text.
> dgc-528: Hide block if no sessions are associated with user

- config/default/views.view.my_sessions_schedule.yml
- config/default/views.view.sessions_schedule.yml
This is to test @alisonjo2786 configuration additions.
> DGC-533: New scheduling config added.

- docroot/modules/custom/capitalcamp_glue/capitalcamp_glue.install
- docroot/themes/custom/twentyseventeen/sass/components/footer/_footer.scss
Adding the links to the 2015 and 2016 archive links to the footer and styling them per: https://drupal4gov.atlassian.net/browse/DGC-71.
> DGC-71: Adding 2016 and 2015 archive links to footer and styling them.

- config/default/taxonomy.vocabulary.conference_year.yml
- docroot/modules/custom/capitalcamp_glue/capitalcamp_glue.install
https://drupal4gov.atlassian.net/browse/DGC-153
> DGC-153: Create Conference Year Vocabulary

- docroot/themes/custom/twentyeighteen/sass/components/hero/_hero.scss
- docroot/themes/custom/twentyeighteen/twentyeighteen.theme
Fixing the bug in https://drupal4gov.atlassian.net/browse/DGC-208
> DGC-208: Fixing mobile and tablet styling for the hero.

- docroot/themes/custom/twentyeighteen/sass/_config.scss
- docroot/themes/custom/twentyeighteen/sass/base/_base.scss
- docroot/themes/custom/twentyeighteen/sass/base/headlines.twig
- docroot/themes/custom/twentyeighteen/sass/base/lists.twig
https://drupal4gov.atlassian.net/browse/DGC-220
> DGC-220: Adding base styles for p, ul, ol, links, and headers.

- docroot/themes/custom/twentyeighteen/sass/_config.scss
- docroot/themes/custom/twentyeighteen/sass/base/_form.scss
- docroot/themes/custom/twentyeighteen/sass/base/form_html.twig
https://drupal4gov.atlassian.net/browse/DGC-214
> DGC-214: Adding text input fields to the style guide.

- docroot/themes/custom/twentyeighteen/sass/_config.scss
- docroot/themes/custom/twentyeighteen/sass/base/_form.scss
- docroot/themes/custom/twentyeighteen/sass/base/form_html.twig
https://drupal4gov.atlassian.net/browse/DGC-217
> DGC-217: Adding fieldsets to the style guide.

- docroot/themes/custom/twentyeighteen/sass/base/_base.scss
- docroot/themes/custom/twentyeighteen/sass/base/table.twig
https://drupal4gov.atlassian.net/browse/DGC-215
> DGC-215: Adding table styles to the style guide.

- config/default/views.view.sponsors_page.yml
- docroot/themes/custom/twentyeighteen/sass/_config.scss
- docroot/themes/custom/twentyeighteen/sass/components/sponsor/_sponsor.scss
- docroot/themes/custom/twentyeighteen/sass/components/sponsor_listing/_sponsor_listing.scss
- docroot/themes/custom/twentyeighteen/templates/views/views-view-unformatted.html.twig
https://drupal4gov.atlassian.net/browse/DGC-221
> DGC-221: Adding sponsor page styling.

- config/default/context.context.2018_theme.yml
- docroot/themes/custom/twentyeighteen/sass/base/_form.scss
Updating the styling for: https://drupal4gov.atlassian.net/browse/DGC-224
> DGC-224: Updating spacing on style registration form.

- docroot/themes/custom/twentyeighteen/package.json
Node and node-sass versions updated.
> DGC-240: Node and node-sass versions updated.

- docroot/themes/custom/twentyeighteen/templates/layout/html.html.twig
https://drupal4gov.atlassian.net/browse/DGC-247
> DGC-247: Updating wording and href of skip to content link

- docroot/themes/custom/twentyeighteen/images/icon-email.svg
- docroot/themes/custom/twentyeighteen/images/icon-facebook.svg
- docroot/themes/custom/twentyeighteen/images/icon-twitter.svg
https://drupal4gov.atlassian.net/browse/DGC-243
> DGC-243: Adding title and aria-labelledby tags to social icon SVGs

- docroot/themes/custom/twentyeighteen/sass/base/_base.scss
https://drupal4gov.atlassian.net/browse/DGC-265
> DGC-265: Removing bottom border of Session Description field 

- docroot/themes/custom/twentyeighteen/package-lock.json
- docroot/themes/custom/twentyeighteen/sass/_config.scss
- docroot/themes/custom/twentyeighteen/sass/components/footer/_footer.scss
- docroot/themes/custom/twentyeighteen/sass/components/navigation/_main-menu.scss
- docroot/themes/custom/twentyeighteen/sass/components/navigation/_user-menu.scss
Due to the older issue branch being out of sync with master, the changes were added to this new branch. Also, for increased legibility, letter spacing was increased for menu items.
> DGC-273: Revised Menu Contrast Issues

- docroot/themes/custom/twentyeighteen/sass/components/views/_schedule.scss
https://drupal4gov.atlassian.net/browse/DGC-245
> DGC-245: Updating styles for h2 and h3 in the schedule to remove bottom padding

- docroot/themes/custom/twentyeighteen/sass/components/views/_schedule.scss
https://drupal4gov.atlassian.net/browse/DGC-320
> dgc-158: Adding styling for the add/remove button on the schedule view.

- blt/scripts/frontend-build.sh
- blt/scripts/frontend-setup.sh
- docroot/themes/custom/twentynineteen/package-lock.json
- docroot/themes/custom/twentynineteen/sass/components/atoms/form/_form.scss
- docroot/themes/custom/twentynineteen/sass/components/views/_schedule.scss
https://drupal4gov.atlassian.net/browse/DGC-350
> DGC-350: update shell scripts for new theme

- docroot/themes/custom/twentynineteen/sass/base/variables/_colors.scss
- docroot/themes/custom/twentynineteen/sass/components/atoms/buttons/_buttons.scss
- docroot/themes/custom/twentynineteen/sass/components/atoms/form/_form.scss
https://drupal4gov.atlassian.net/browse/DGC-396
> DGC-396: Update form styles for Submit a Session and Registration pages.

- README.md
Corrects the BLT documentation link.
> DGC-769: Updates README.

- config/default/twentynineteen.settings.yml
https://drupal4gov.atlassian.net/browse/DGC-405
> DGC-405: update favicon in config.

- docroot/themes/custom/twentynineteen/sass/base/variables/_colors.scss
- docroot/themes/custom/twentynineteen/sass/components/navigation/_main-menu.scss
- docroot/themes/custom/twentynineteen/sass/components/navigation/_user-menu.scss
- docroot/themes/custom/twentynineteen/sass/components/regions/_footer.scss
https://drupal4gov.atlassian.net/browse/DGC-414
> DGC-414: Global Site Updates

- docroot/themes/custom/twentynineteen/sass/components/regions/_footer.scss
https://drupal4gov.atlassian.net/browse/DGC-392
> DGC-392: fix excessive spacing on footer SVGs.

- docroot/themes/custom/twentynineteen/sass/components/views/_schedule.scss
- docroot/themes/custom/twentynineteen/sass/components/views/schedule.twig
https://drupal4gov.atlassian.net/browse/DGC-422
> DGC-422: Update schedule styling with exposed filter.

- docroot/themes/custom/twentynineteen/sass/_print.scss
https://drupal4gov.atlassian.net/browse/DGC-430
> DGC-430: uncomment print styles.

- config/default/core.entity_view_display.user.user.default.yml
https://drupal4gov.atlassian.net/browse/DGC-425
> DGC-425: update website, move job title up.

- docroot/themes/custom/twentynineteen/sass/base/_base.scss
- docroot/themes/custom/twentynineteen/sass/base/variables/_colors.scss
- docroot/themes/custom/twentynineteen/sass/base/variables/_fonts.scss
- docroot/themes/custom/twentynineteen/sass/components/_breadcrumb.scss
- docroot/themes/custom/twentynineteen/sass/components/_messages.scss
- docroot/themes/custom/twentynineteen/sass/components/_session-form.scss
- docroot/themes/custom/twentynineteen/sass/components/atoms/a/_a.scss
- docroot/themes/custom/twentynineteen/sass/components/atoms/blockquote/_blockquote.scss
- docroot/themes/custom/twentynineteen/sass/components/atoms/buttons/_buttons.scss
- docroot/themes/custom/twentynineteen/sass/components/atoms/form/_form.scss
- docroot/themes/custom/twentynineteen/sass/components/atoms/hr/_hr.scss
- docroot/themes/custom/twentynineteen/sass/components/atoms/table/_table.scss
- docroot/themes/custom/twentynineteen/sass/components/atoms/typography/_typography.scss
- docroot/themes/custom/twentynineteen/sass/components/blocks/_aside_blocks.scss
- docroot/themes/custom/twentynineteen/sass/components/blocks/hero/_hero.scss
- docroot/themes/custom/twentynineteen/sass/components/navigation/_main-menu.scss
- docroot/themes/custom/twentynineteen/sass/components/navigation/_user-menu.scss
- docroot/themes/custom/twentynineteen/sass/components/regions/_content.scss
- docroot/themes/custom/twentynineteen/sass/components/regions/_footer.scss
- docroot/themes/custom/twentynineteen/sass/components/views/_announcements.scss
- docroot/themes/custom/twentynineteen/sass/components/views/_proposed-sessions.scss
- docroot/themes/custom/twentynineteen/sass/components/views/_schedule.scss
- docroot/themes/custom/twentynineteen/sass/components/views/_sponsors.scss
- docroot/themes/custom/twentynineteen/twentynineteen.libraries.yml
https://drupal4gov.atlassian.net/browse/DGC-438
This is theme only changes, no config.
> DGC-438: Update theme with new colors, updates to support new comps.

- docroot/themes/custom/twentynineteen/sass/base/_mixins.scss
- docroot/themes/custom/twentynineteen/sass/base/variables/_colors.scss
- docroot/themes/custom/twentynineteen/sass/components/atoms/buttons/_buttons.scss
- docroot/themes/custom/twentynineteen/sass/components/atoms/lists/_lists.scss
- docroot/themes/custom/twentynineteen/sass/components/atoms/table/_table.scss
- docroot/themes/custom/twentynineteen/sass/components/blocks/_aside_blocks.scss
- docroot/themes/custom/twentynineteen/sass/components/blocks/call-to-action/_call-to-action.scss
- docroot/themes/custom/twentynineteen/sass/components/navigation/_main-menu.scss
- docroot/themes/custom/twentynineteen/sass/components/regions/_content.scss
- docroot/themes/custom/twentynineteen/sass/components/regions/_footer.scss
- docroot/themes/custom/twentynineteen/sass/layout/_panels.scss
- docroot/themes/custom/twentynineteen/sass/layout/_sidebars.scss
- docroot/themes/custom/twentynineteen/sass/styles.scss
https://drupal4gov.atlassian.net/browse/DGC-450
> DGC-450: Update table, lists, button, colors.

- docroot/themes/custom/twentynineteen/sass/components/atoms/form/_form.scss
- docroot/themes/custom/twentynineteen/sass/components/views/_schedule.scss
https://drupal4gov.atlassian.net/browse/DGC-468
> DGC-468: Styling some forms, and the schedule page.

- docroot/themes/custom/twentynineteen/sass/components/blocks/_banner-block.scss
- docroot/themes/custom/twentynineteen/templates/blocks/block--bundle--banner.html.twig
https://drupal4gov.atlassian.net/browse/DGC-451
> DGC-451: Update to make banner 100%.

- config/default/core.entity_view_display.node.session.default.yml
- docroot/themes/custom/twentynineteen/sass/components/_session-form.scss
- docroot/themes/custom/twentynineteen/sass/components/atoms/form/_form.scss
https://drupal4gov.atlassian.net/browse/DGC-483
> DGC-482: Update form label color.

- docroot/themes/custom/twentynineteen/sass/components/atoms/form/_form.scss
https://drupal4gov.atlassian.net/browse/DGC-482
> DGC-482: Update other field labels to have gold background.
